name: Build and publish
# This workflow is triggered on new tags
on:
  push:
    tags:
    - '*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        uses: ./.github/actions/buildall
        with:
          name: myDocker/repository
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
